if(NOT EXISTS "${PROTOC_PATH}")
    message(FATAL_ERROR "PROTOC_PATH must point to host protoc 3.21.12")
endif()
execute_process(COMMAND "${PROTOC_PATH}" --version OUTPUT_VARIABLE PROTOC_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT PROTOC_VERSION STREQUAL "libprotoc 3.21.12")
    message(FATAL_ERROR "Expected protoc 3.21.12, got ${PROTOC_VERSION}")
endif()
set(protobuf_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(protobuf_BUILD_PROTOC_BINARIES OFF CACHE BOOL "" FORCE)
set(protobuf_BUILD_LIBPROTOC ON CACHE BOOL "" FORCE)
set(protobuf_WITH_ZLIB OFF CACHE BOOL "" FORCE)
set(PNG_TESTS OFF CACHE BOOL "" FORCE)
set(PNG_SHARED OFF CACHE BOOL "" FORCE)
set(EXPAT_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(EXPAT_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(EXPAT_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(EXPAT_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(PCRE2_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(PCRE2_BUILD_PCRE2GREP OFF CACHE BOOL "" FORCE)
enable_language(ASM)
add_subdirectory("${SRC}/boringssl" boringssl EXCLUDE_FROM_ALL)
add_subdirectory("${SRC}/pcre" pcre EXCLUDE_FROM_ALL)
foreach(LIB libcutils libselinux libsepol libpackagelistparser)
    include("${FORGE_SDK_SOURCE}/lib/${LIB}.cmake")
endforeach()
target_include_directories(libselinux PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/pcre")
get_target_property(SEPOL_DEFINITIONS libsepol COMPILE_DEFINITIONS)
list(REMOVE_ITEM SEPOL_DEFINITIONS HAVE_REALLOCARRAY)
set_property(TARGET libsepol PROPERTY COMPILE_DEFINITIONS "${SEPOL_DEFINITIONS}")
file(READ "${SRC}/core/libcutils/native_handle.cpp" NATIVE_HANDLE_SOURCE)
string(REPLACE "#if !defined(__BIONIC__)" "#if !defined(__BIONIC__) || __ANDROID_API__ < 29" NATIVE_HANDLE_SOURCE "${NATIVE_HANDLE_SOURCE}")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/compat/native_handle.cpp" "${NATIVE_HANDLE_SOURCE}")
get_target_property(CUTILS_SOURCES libcutils SOURCES)
list(REMOVE_ITEM CUTILS_SOURCES "${SRC}/core/libcutils/native_handle.cpp")
set_property(TARGET libcutils PROPERTY SOURCES "${CUTILS_SOURCES};${CMAKE_CURRENT_BINARY_DIR}/compat/native_handle.cpp")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/incfs-sysprop/include")
configure_file("${FORGE_SDK_SOURCE}/patches/misc/IncrementalProperties.sysprop.h" "${CMAKE_CURRENT_BINARY_DIR}/incfs-sysprop/include/IncrementalProperties.sysprop.h" COPYONLY)
configure_file("${FORGE_SDK_SOURCE}/patches/misc/IncrementalProperties.sysprop.cpp" "${CMAKE_CURRENT_BINARY_DIR}/incfs-sysprop/IncrementalProperties.sysprop.cpp" COPYONLY)
include("${FORGE_SDK_SOURCE}/lib/libincfs.cmake")
get_target_property(INCFS_SOURCES libincfs SOURCES)
list(REMOVE_ITEM INCFS_SOURCES "${SRC}/incremental_delivery/sysprop/IncrementalProperties.sysprop.cpp")
set_property(TARGET libincfs PROPERTY SOURCES "${INCFS_SOURCES};${CMAKE_CURRENT_BINARY_DIR}/incfs-sysprop/IncrementalProperties.sysprop.cpp")
target_include_directories(libincfs PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/incfs-sysprop/include")
target_link_libraries(libincfs PRIVATE crypto)
add_subdirectory("${SRC}/protobuf" protobuf EXCLUDE_FROM_ALL)
foreach(TARGET libprotobuf libprotobuf-lite libprotoc)
    if(TARGET ${TARGET})
        target_include_directories(${TARGET} PRIVATE "${SRC}/protobuf/android")
    endif()
endforeach()
add_subdirectory("${SRC}/libpng" libpng EXCLUDE_FROM_ALL)
add_subdirectory("${SRC}/expat/expat" expat EXCLUDE_FROM_ALL)
include("${FORGE_SDK_SOURCE}/lib/libandroidfw.cmake")
include("${FORGE_SDK_SOURCE}/lib/libbuildversion.cmake")
target_sources(libutils PRIVATE
    "${SRC}/core/libutils/binder/RefBase.cpp"
    "${SRC}/core/libutils/binder/StrongPointer.cpp"
    "${SRC}/core/libutils/FileMap.cpp"
    "${SRC}/core/libutils/JenkinsHash.cpp"
    "${SRC}/core/libutils/binder/Errors.cpp"
    "${SRC}/core/libutils/binder/String8.cpp"
    "${SRC}/core/libutils/binder/String16.cpp"
    "${SRC}/core/libutils/binder/Unicode.cpp")
target_include_directories(libutils PRIVATE "${SRC}/libbase/include")
target_sources(libutils PRIVATE
    "${SRC}/logging/liblog/log_event_write.cpp"
    "${SRC}/logging/liblog/log_event_list.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/security_log_compat.cpp")

# Generate into the build directory; pinned source checkouts remain unchanged.
set(PROTO_DIR "${CMAKE_CURRENT_BINARY_DIR}/aapt-proto")
file(MAKE_DIRECTORY "${PROTO_DIR}")
file(GLOB PROTO_INPUTS "${SRC}/base/tools/aapt2/*.proto")
set(AAPT2_PROTO_SRC)
set(AAPT2_PROTO_HDRS)
foreach(INPUT IN LISTS PROTO_INPUTS)
    get_filename_component(NAME "${INPUT}" NAME)
    get_filename_component(STEM "${INPUT}" NAME_WE)
    file(READ "${INPUT}" CONTENT)
    string(REPLACE "frameworks/base/tools/aapt2/" "" CONTENT "${CONTENT}")
    file(WRITE "${PROTO_DIR}/${NAME}" "${CONTENT}")
endforeach()
foreach(INPUT IN LISTS PROTO_INPUTS)
    get_filename_component(NAME "${INPUT}" NAME)
    get_filename_component(STEM "${INPUT}" NAME_WE)
    execute_process(COMMAND "${PROTOC_PATH}" "--proto_path=${PROTO_DIR}" "--cpp_out=${PROTO_DIR}" "${PROTO_DIR}/${NAME}"
        RESULT_VARIABLE PROTO_RESULT)
    if(NOT PROTO_RESULT EQUAL 0)
        message(FATAL_ERROR "protoc failed for ${NAME}")
    endif()
    list(APPEND AAPT2_PROTO_SRC "${PROTO_DIR}/${STEM}.pb.cc")
    list(APPEND AAPT2_PROTO_HDRS "${PROTO_DIR}/${STEM}.pb.h")
endforeach()
include_directories(BEFORE "${PROTO_DIR}")
include_directories(BEFORE "${SRC}/native/libs/binder/include")
# Reuse the pinned upstream source list, bypassing its in-source proto generator.
file(READ "${FORGE_SDK_SOURCE}/build-tools/aapt2.cmake" RECIPE)
string(FIND "${RECIPE}" "set(INCLUDES" RECIPE_START)
string(SUBSTRING "${RECIPE}" ${RECIPE_START} -1 RECIPE)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/aapt2-recipe.cmake" "${RECIPE}")
include("${CMAKE_CURRENT_BINARY_DIR}/aapt2-recipe.cmake")
target_include_directories(libaapt2 PRIVATE "${SRC}/expat/expat/lib" "${CMAKE_CURRENT_BINARY_DIR}/libpng")
target_include_directories(aapt2 PRIVATE "${SRC}/expat/expat/lib" "${CMAKE_CURRENT_BINARY_DIR}/libpng")
target_include_directories(libandroidfw PRIVATE "${SRC}/expat/expat/lib" "${CMAKE_CURRENT_BINARY_DIR}/libpng")
